export default  {
    THEME_CHANGE:'THEME_CHANGE',
    THEME_INIT:'THEME_INIT',
    //这个是popular新增的三个action
    POPULAR_REFRESH:'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS',
    //增加上拉加载的俩种类型
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',
    POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL',


}